---
- name: "Push TLS cert /etc/prosody/certs/"
  ansible.builtin.copy:
    content: "{{ item.cert }}"
    dest: "/etc/prosody/certs/{{ item.name }}.crt"
    owner: root
    group: prosody
    mode: 0640
  when: item.cert is defined
  tags:
    - certs-jabber
  notify: Reload prosody config

- name: "Push TLS key to /etc/prosody/certs/"
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/etc/prosody/certs/{{ item.name }}.key"
    owner: root
    group: prosody
    mode: 0640
  when: item.key is defined
  tags:
    - certs-jabber
  notify: Reload prosody config
