# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

cluster = {
  "jessie"  => { :ip => "192.168.33.10", },
  "stretch" => { :ip => "192.168.33.11", }
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  cluster.each_with_index do |(hostname, vars), index|

    # Virtualbox
    config.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
    
    config.vm.network :private_network, ip: "#{vars[:ip]}"
    config.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'rsync'

    # Debian
    config.vm.define hostname do |node|
      node.vm.hostname = hostname
      node.vm.box = "debian/#{hostname}64"

      # Ansible
      node.vm.provision "ansible_local" do |ansible|
        ansible.install_mode = "pip"
        ansible.version = "2.4.4.0"
        ansible.playbook = "/etc/ansible/roles/role_under_test/tests/test.yml"
        ansible.become = true
        ansible.compatibility_mode = "2.0"
      end
    end
  end

end
